version: '3'

services:
  app:
    build: # Dockerfileの設定
      context: . # Dockerfileがあるディレクトリ
      dockerfile: Dockerfile # Dockerfileの名前
    container_name: react-ts-vite
    image: node:18-alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment: # 環境変数
      - HOST=0.0.0.0 # localhost接続をする際に必要
      - CHOKIDAR_USEPOLLING=true # ホットリロードを可能にする
    tty: true
    ports:
      - '5173:5173'
    command: sh -c "npm install && npm run dev"
